### ISSUE TITLE
Cannot perform POST, PUT, Delete actions

### ISSUE THREAD

**Issue by cwbrandsma** [nfarina/webrequest#4]
It could be I am just ignorant, but I cannot perform POST, PUT, or DELETE actions with SMWebRequest.

If you change the request property to use SMMutableUrlRequest then I will be able to do this.

If I am in error, can you please update a sample to show how to do this?

Thank you.

**Comment by nfarina** [comment]
Hello,

You can feed an `NSMutableURLRequest` to `SMWebRequest` to accomplish this, here's an example:

```
    NSMutableURLRequest *URLRequest = [NSMutableURLRequest requestWithURL:URL];
    URLRequest.HTTPMethod = @"POST";

    SMWebRequest *request = [SMWebRequest requestWithURLRequest:URLRequest delegate:nil context:NULL];
    [request addTarget:self action:@selector(requestComplete:) forRequestEvents:SMWebRequestEventComplete];
    [request start];
```

Let me know if this works for you!

**Comment by cwbrandsma** [comment]
OK, I can do that.  But, for my framework the majority of my requests are POSTs (lots of GETs too, just lots of POSTs)

Is there a reason you would not want to use SMMutableURLRequest by default?

**Comment by nfarina** [comment]
I don't know if I fully understand—how would you like the `SMWebRequest` API to be changed exactly?

**Comment by nfarina** [comment]
Hi, I'm closing this since it's been open for some time - feel free to comment again if you had any further thoughts!
