### ISSUE TITLE
CocoaPod

### ISSUE THREAD

**Issue by mokagio** [nfarina/webrequest#7]
Hi there! I love the `SMWebRequest`, why there's no pod on [CocoaPods](cocoapods.org)?

**Comment by nfarina** [comment]
I went ahead and added CocoaPods support and requested them to add it:
https://github.com/CocoaPods/Specs/pull/975

Hopefully they will. Thanks for the request and glad you're enjoying SMWebRequest!

**Comment by mokagio** [comment]
They added it in less than an hour. Sweet! :)

**Comment by nfarina** [comment]
Yeah they're on top of things there!
